# Generated by Django 4.0 on 2022-02-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'admin')]),
        ),
    ]
