# Generated by Django 4.0 on 2022-02-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_alter_ownermodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownermodel',
            name='surname',
        ),
    ]
