# Generated by Django 4.0 on 2022-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_remove_ownermodel_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ownermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
