# Generated by Django 4.0 on 2022-02-07 20:02

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_ownermodel_created_at_ownermodel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, null=True)),
                ('genus', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=70, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('age', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='veterinary.ownermodel')),
            ],
            options={
                'verbose_name': 'Owner',
            },
        ),
    ]
