# Generated by Django 4.0 on 2022-02-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_animalmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalmodel',
            options={'verbose_name': 'Animal'},
        ),
    ]
