# Generated by Django 4.0 on 2022-02-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('veterinary', '0007_ownermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.customusermodel'),
        ),
        migrations.AlterField(
            model_name='ownermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.customusermodel'),
        ),
    ]
