# Generated by Django 4.0 on 2022-02-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_alter_animalmodel_owner_alter_ownermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='veterinary.ownermodel'),
        ),
    ]
